# Generated by Django 3.0.4 on 2020-04-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=13, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'apos'), ('A-', 'aneg'), ('B+', 'bpos'), ('B-', 'bneg'), ('O+', 'opos'), ('O-', 'oneg'), ('AB+', 'abpos'), ('AB-', 'abneg')], max_length=3)),
                ('patient_photo_file_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiabeticRetinopathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retina_photo_path', models.CharField(max_length=100)),
                ('predicted_stage', models.CharField(max_length=10)),
                ('confirmation', models.CharField(max_length=5)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='DiabeticHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetic_type', models.CharField(max_length=6)),
                ('sugar_Fasting_value', models.CharField(max_length=15)),
                ('sugar_Non_fasting_value', models.CharField(max_length=15)),
                ('time_duration', models.IntegerField()),
                ('diab_report_path', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRapp.Patient')),
            ],
        ),
    ]
